### ISSUE TITLE
Notice when enabling the module

### ISSUE THREAD

**Issue by sentaidigital** [backdrop-contrib/feeds#1]
When I enabled the Feeds and Feeds UI module, the following notice was generated about 15 times:

> Notice: Undefined index: module in feeds_system_info_alter() (line 742 of /path/to/backdrop-root/modules/feeds/feeds.module).

**Comment by Al-Rozhkov** [comment]
Confirm. I have same notices in my log. Will try to fix it.

**Comment by docwilmot** [comment]
I cant duplicate this. Need more info please.
