### ISSUE TITLE
PHP 8.1 - Deprecated: Optional parameter $feed_nid declared before required parameter $context is implicitly treated as a required parameter 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/feeds#100]
Changed Lando settings to PHP 8.1 and this appears at the top of the screen

```
Deprecated: Optional parameter $feed_nid declared before required parameter $context is implicitly treated as a required parameter in /app/www/modules/feeds/feeds.module on line 298
```

https://github.com/backdrop-contrib/feeds/blob/9b4da2b41208ed5bcdc11884b241538e9f8c3c0f/feeds.module#L298

Pull request to follow

**Comment by herbdool** [comment]
I made a different parameter fix with your PR @yorkshire-pudding. It's now merged but could use your testing before a release.
