### ISSUE TITLE
Feeds plugin names may be different from their handler class

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/feeds#108]
I'm running into an issue while porting Feeds Entity Processor. This issue only exists in Backdrop's version of Feeds.

## Background:
Feeds Entity Processor creates separate feeds plugins for each entity in the site (this includes core and custom entities). Each of those plugins use on of 6 standard handler class  provided by the module (e.g.  `FeedsEntityProcessor`, which is a standard handler for all entities).

## Problem:
When feeds was ported and ctools was removed, we ended up with some faulty code in function `feeds_plugin()` that only  shows up in the case above: when the plugin name does NOT coincide with the handler class. For example, a plugin called `FeedsEntityProcessorEvent` that uses handler `FeedsEntityProcessor`.

Line 1270 of feeds.module checks if the class exists. To do so, it uses the plugin NAME, not the handler class name.  Since the class doesn't exist, it fails. 

All feeds plugins provided by feeds itself happen to have plugin names that coincide with the handler class name, but as seen above, this is not necessarily the case. D7 Feeds accounted for this through the CTools system.  

## Solution:
I'll provide a PR.

**Comment by argiepiano** [comment]
PR #109

**Comment by argiepiano** [comment]
This issue is a blocker for the release of [Feeds Entity Processor](https://github.com/backdrop-contrib/feeds_entity_processor)

**Comment by argiepiano** [comment]
Maintainers, any chance you may be able to look at this issue and PR? @docwilmot and @herbdool

**Comment by herbdool** [comment]
I've merged this and other PRs. Could use someone to test before I release.
