### ISSUE TITLE
Feeds user import - attempts to insert instead of update

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/feeds#110]
I used Feeds to import users on a D7 site many times in the past, so am confused why this isn't working in Backdrop.
I have an upgraded site with hundreds of users successfully carried over from a D7 site. When I try to use Feeds to import and update changed user accounts, I'm getting this error:

Integrity constraint violation: 1062 Duplicate entry '80-5' for key 'PRIMARY' 

(where 80 is the id of an existing user).

I've set the User Processor settings to either of "Insert new user accounts" or "Do not insert new user accounts" (makes no difference eitehr way) and "Update existing user accounts" is on.

and the mapping such that user is a unique identifier.

Any clues about what's going wrong here? I'm not sure where to look to find more detail.

Recent log messages shows:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '80-5' for key 'PRIMARY': INSERT INTO {users_roles} (`uid`, `role`) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1), ...

Thanks
Martin

**Comment by herbdool** [comment]
@nattywebdev can you check to see if you still have the same problem with the latest release? Thanks

**Comment by herbdool** [comment]
@nattywebdev this might help: https://github.com/backdrop-contrib/feeds/pull/116. Also make sure to use Search roles by role name and not label.

**Comment by nattywebdev** [comment]
Many thanks @herbdool - I'll check it out and let you know.

**Comment by marcus-leonard** [comment]
This may still be an issue.
Latest Bd (1.28.2) and Feeds (1.x-1.1.5).

If I import users without roles in the CSV File, and set Feeds user processor config to add the role under "Additional roles", the import throws the above error.
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry...` etc.

To get the import to work, I have to have no roles selected under "Additional roles" and put the role into the CSV file (and map the column to roles). If I do this it works fine.
