### ISSUE TITLE
Importing users from CSV with mapping "Search roles by: Role label" doesn't work

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/feeds#111]
## Description
Importing users with from a CSV sheet and mapping user roles with the setting "Search roles by: Role label" doesn't work.

## Steps to reproduce
1. Start with a CSV sheet with 3 columns: NAME, EMAIL, ROLE. Fill with values. In Roles use the role  LABEL (not machine name) (e.g. 'Editor')
2. Create a feeds importer with the following mapping:
NAME -> User name (name). Mark it as "unique"
EMAIL -> Email address (mail). Mark as "unique"
ROLE -> User roles (roles_list). Configure to: "Search roles by: Role label"

3. In the "User processor" configuration, leave all defaults untouched.
4. Import the CSV
5. Visit the UI for user accounts admin/people

## Actual behavior
None of the imported users have a role assigned

## Expected behavior
Users should have a role assigned

## Additional information
If you change the setting to "Search roles by: Role name" AND change the ROLE column in the CSV file to the machine name of the role (e.g. `editor`), then the import works as expected.

Backdrop 1.22.0
Feeds: 1.x as of July 9 2022

**Comment by argiepiano** [comment]
In part the confusion comes (I believe) from the changes in roles in BAckdrop.

The roles objects looked like this:

Drupal 7:
- rid (role ID, main identifier for roles. `user_role_load()`)
- name (a machine name, used for human identifier, and by `user_role_load_by_name()`)
- weight

Backdrop
- name (a machine name, the main identifier for the roles. used by `user_role_load()`)
- label (a human readable label, typically with uppercase first letter as in Editor)
- weight

The D7 User feeds version has two options for Roles
- Search roles by name (which uses `user_role_load_by_name()`)
- Search roles by Role ID (which uses `user_role_load()`

When Feeds was ported to Backdrop, they renamed the two options, but the second option below doesn't work:
- Search roles by name (which uses `user_role_load()`
- Search roles by label (which ALSO uses `user_role_load()` and therefore doesn't find anything since the CSV provides Backdrop's role labels as in "Editor")

Pasting the actual code that does the loading of the role, taken from `FeedsUserProcessor::rolesListSetTarget()`. You see that both `case` do the same thing. There is no way in Backdrop to load a user role by label, so I suggest just removing this option.

```php
switch ($mapping['role_search']) {
        case self::ROLE_SEARCH_LABEL:
          $role = user_role_load($value);
          if (!$role && !empty($mapping['autocreate'])) {
            // Create new role if role doesn't exist.
            $role = new stdClass();
            $role->label = $value;
            user_role_save($role);
            $role = user_role_load($role->label);
          }
          break;

        case self::ROLE_SEARCH_NAME:
          $role = user_role_load($value);
          break;
      }
```

**Comment by herbdool** [comment]
Happy to accept a PR.

**Comment by herbdool** [comment]
I've got a PR removing it.

**Comment by argiepiano** [comment]
Thank you, @herbdool! I've tested, and it works for me (except the option "Automatically create roles" - ~~but that is not related to this PR. I'll create another issue for this~~).

I'm going to leave a suggestion in the PR. Since the CSV must include the role machine name, I feel it would be helpful to display it in "Allowed roles" widget settings (see image). Currently only the human label is displayed there.  

<img width="296" alt="Screen Shot 2022-07-12 at 12 11 47 PM" src="https://user-images.githubusercontent.com/9938978/178565640-6a62aebb-5611-4db2-aec0-9e699cbf6f9c.png">

**Comment by argiepiano** [comment]
I added another comment about autocreate. The PR actually removes this functionality (but the option is still shown in the UI). I suggested a way to approach this in the comment.

**Comment by argiepiano** [comment]
@herbdool I've create a PR into the issue-111 branch of feeds. I'm not sure if this will work for merging. PR #118.

It adds back user role autocreate functionality.

- If the role name is non-numeric, the label is created based on the role machine name by capitalizing the first letter and converting _ to space
- If the role is numeric (e.g. because this is an export of role ID from a D7 site), the default "Role N" is created, where N is the D7 role ID

I've done some testing in both situations and it seems to work well. New user roles are created.
