### ISSUE TITLE
PHP 8.1 - Deprecated function in FeedsDateTime

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/feeds#112]
While testing #100 - when I start creating a feed on the 8.1 test site, I get the following warnings:

Deprecated function: Return type of FeedsDateTime::__wakeup() should either be compatible with DateTime::__wakeup(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in require_once() (line 702 of /app/docroot/modules/feeds-1.x/plugins/FeedsParser.inc).

Deprecated function: Return type of FeedsDateTime::setTimezone($tz, $force = false) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in require_once() (line 702 of /app/docroot/modules/feeds-1.x/plugins/FeedsParser.inc).

**Comment by herbdool** [comment]
Thanks @yorkshire-pudding. I took a look at FeedsDateTime and FeedsDateTimeElement and noticed that they're both marked as deprecated. So I figure it might be a good time to remove them entirely. I've got a PR that does so. Would you be able to test it? I think you might need to create a feed that included some dates to parse and see if you get errors or not. Thanks!

**Comment by yorkshire-pudding** [comment]
Thanks @herbdool - I've tested your PR on a view with created (aka post) date (of the node) and it worked perfectly.  I set both sites to be Europe/London and the time came across accurately.  No new warnings or debug messages.

**Comment by herbdool** [comment]
Great! Thanks @yorkshire-pudding. I think I'll merge and make a new release.
