### ISSUE TITLE
Fatal error: Cannot redeclare entityreference_feeds_set_target()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/feeds#121]
I have an issue with a feed importer that has two entity reference fields (not sure if the number is a problem). 

If I go to edit mapping or if I try to run the importer, I get the following error

```quote
Fatal error: Cannot redeclare entityreference_feeds_set_target() (previously declared in /app/docroot/modules/contrib/entityreference/entityreference.feeds.inc:74) in /app/docroot/modules/contrib/feeds/mappers/entityreference.inc on line 71
```

The two entity reference fields within the feed importer config are:

```json
                    {
                        "source": "Location",
                        "target": "field_location_ref:etid",
                        "unique": false,
                        "language": "und"
                    },
                    {
                        "source": "Schedule ID",
                        "target": "field_service_schedule:etid",
                        "unique": false,
                        "language": "und"
                    },
```

I am using feeds in a slightly unusual way.  I am using repeating_dates to create a schedule in a node.  Then I create a CSV view that includes the `nid` of the entities in question and shows each instance in the repeating_dates series as a row; `field_location_ref` refers to another content type. Then I use CSV importer to import each date entry as a new node, updating and deleting as appropriate.

This worked when I first created it and tested it but has stopped working so I wonder if it is the latest release, specifically Issue #119 that was introduced but entityreference is not actually in released core.

**Comment by yorkshire-pudding** [comment]
If I rename `mappers/entityreference.inc` to `mappers/entityreference.inc.disabled` then I can both access the mapping and run the importer.  Looks like this needs a temporary fix until entityreference is actually in core.

**Comment by Schnitzer** [comment]
+1
Same behavior, cannot open the mappings page and get the same error.

**Comment by yorkshire-pudding** [comment]
@Schnitzer - if you follow my tip above it should work.
@herbdool - please can you look at this?

**Comment by herbdool** [comment]
I've removed it from entity reference https://github.com/backdrop-contrib/entityreference/releases/tag/1.x-1.7.2
