### ISSUE TITLE
Impossible to import per language

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/feeds#122]
Backdrop differs quite a bit re entity keys and translation abilities.

Struggling with it. At first sight I thought it's the usual language/langcode mixup as suggested in https://github.com/backdrop-contrib/feeds/issues/105, but it goes beyond that.

It's currently not even possible to *select* a language other than neutral, if i18n isn't installed.

**Comment by indigoxela** [comment]
With #123 applied I got the language aware import working with nodes. We need to test taxonomy terms, too.

**Comment by indigoxela** [comment]
Things to verify: is "translation" the right key for all entity types? My assumption is based on:

- https://github.com/backdrop/backdrop/blob/1.x/core/modules/entity/entity.api.php#L130
- https://github.com/backdrop/backdrop/blob/1.x/core/modules/entity/entity.module#L348

**Comment by indigoxela** [comment]
Testing is a bit complex. My setup might give some hints:

- On another site I created a view to export a feed of (translatable) nodes
- The same nodes I wanted to import in a Backdrop site (but the langcode should be kept)

The settings (roughly):

- Attached to: none
- Periodic import: off
- Import on submission
- HTTP Fetcher
- Download content from a URL.
- Common syndication parser
- Parse RSS and Atom feeds.
- Node processor
- Create and update nodes.

There's no way to set a "dynamic" language with RSS (same as in Drupal IIRC), so I created two importers - one for each language.

**Comment by herbdool** [comment]
Now that I've merged your PR to get tests running they're running on this one. As expected many still don't work but shouldn't stop this one from being merged. (I won't be able to look more closely for a couple weeks so someone else could)

**Comment by herbdool** [comment]
It looks pretty legit. `translation` is always assigned in https://github.com/backdrop/backdrop/blob/1.x/core/modules/entity/entity.module#L348.
