### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/feeds#124]
@herbdool and/or @docwilmot what's actually the state of the automated tests for feeds. Which ones work, which ones don't?

**Comment by herbdool** [comment]
I don't know if any of them work. I might have already made an issue (I can't recall) because it was clear that tests needed a lot of work.

**Comment by indigoxela** [comment]
I didn't find any issue - open or closed. I just found it strange, that no tests run for PRs (would have provided a GHA if it were only that).

> it was clear that tests needed a lot of work.

Oh dear, that for sure...

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop-contrib/feeds/pull/125).

I got a handful of tests working, the GitHub workflow will not run until it's merged, I guess. @herbdool what do you think?

**Comment by herbdool** [comment]
Thanks @indigoxela! I've merged. I'm guessing no tests will run until there's a new PR after this?

**Comment by indigoxela** [comment]
> I've merged

Oops, I forgot to add the dependency to the workflow. :disappointed:

**Comment by indigoxela** [comment]
Now we can see it in (failing) [action](https://github.com/backdrop-contrib/feeds/pull/126)

Seems like 8 out of ~43 tests are currently passing, so there's still a long way to go. But the first step is made. :smirk: Hope that motivates others to chime in and fix another test.
