### ISSUE TITLE
PHP notice Undefined index: module in feeds_system_info_alter()

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#13]
I'm seeing my dblog flodded with the following PHP notices:
```
Notice: Undefined index: module in feeds_system_info_alter() (line 819 of backdrop/modules/contrib/feeds/feeds.module).
```

The following code...
```php
    if ($file->name === $plugin['module']) {
      $module_plugins[$plugin_id] = TRUE;
    }
```
...should be replaced as follows:
```php
    if (array_key_exists('module', $plugin) && $file->name === $plugin['module']) {
      $module_plugins[$plugin_id] = TRUE;
    }
```

---

PR: https://github.com/backdrop-contrib/feeds/issues/13

**Comment by jenlampton** [comment]
Hm, I'm unable to reproduce this on the 1.x branch... but pushing my PR anyway. Perhaps it will help someone else.

**Comment by ghost** [comment]
I haven't tested it, but I believe @jenlampton's PR would prevent the notices appearing. However, it doesn't fix the root problem, which is that `feeds_get_plugins()` (which is where `$plugin['module']` comes from) doesn't actually have a `module` key at all...

Here's one of the array keys returned by `feeds_get_plugins()`:
```
FeedsNodeProcessor (Array, 4 elements)
  name (String, 14 characters ) Node processor
  description (String, 24 characters ) Create and update nodes.
  help (String, 44 characters ) Create and update nodes from parsed content.
  handler (Array, 4 elements)
    parent (String, 14 characters ) FeedsProcessor
    class (String, 18 characters ) FeedsNodeProcessor
    file (String, 22 characters ) FeedsNodeProcessor.inc
    path (String, 37 characters ) ./modules/feeds/plugins
```
No `module` key...

So I think this issue needs some more work (by someone who knows more about how Feeds should work than I do).

**Comment by VasasA** [comment]
@BWPanda Drupal 7 uses `ctools_get_plugins()` function instead of `feeds_get_plugins()` here, and that function provides `module` keys, but that function is not implemented in Backdrop.
(I encountered this bug when converting the ldap_feeds module.)

**Comment by jenlampton** [comment]
Here's some docs on converting feeds plugins for Backdrop:
https://github.com/backdrop-contrib/ctools/wiki/Converting-CTools-plugins

It looks like maybe all that is needed is adding a module key to the plugins? I bet ctools did that automatically, but we can do it explicitly.

**Comment by jenlampton** [comment]
I just ran into this again. It happened immediately when I first installed feeds module.

**Comment by jenlampton** [comment]
I've filed a new PR that adds the missing module key to all feeds plugins in this module: https://github.com/backdrop-contrib/feeds/issues/13

**Comment by stpaultim** [comment]
I'm getting flooded with these errors, which I assume is the same problem - just different line number. 

```
Notice: Undefined index: module in feeds_system_info_alter() (line 896 of backdrop/modules/contrib/feeds/feeds.module)
```

**Comment by jenlampton** [comment]
@stpaultim  have you tested the PR? I just applied that to a new site and it resolved the issue for me.

**Comment by stpaultim** [comment]
@jenlampton I just replaced the feeds module with your branch and I'm no longer flooded with errors, but I am getting a single error. 

`Notice: Undefined index: module in feeds_system_info_alter() (line 896 of /var/www/triplo/all-modules/simplo/src/modules/contrib/feeds/feeds.module).`

I will try to do a little more testing later tonight.

**Comment by jenlampton** [comment]
Do you have any feeds modules enabled? Itay be coming from that one.
