### ISSUE TITLE
Enabled / Disabled setting won't stick

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#14]
I can't seem to disable Feeds importers that I don't want to use on my site. Un-checking the "Enabled" checkbox and saving  the listing does not disable the importer.

<img width="503" alt="screen shot 2018-08-28 at 2 00 13 pm" src="https://user-images.githubusercontent.com/397895/44750646-c16c0e00-aaca-11e8-9abe-f4358411323b.png">

---

PR https://github.com/backdrop-contrib/feeds/pull/27

**Comment by bradbulger** [comment]
Is this setting related to why it keeps rerunning old file imports through cron?

**Comment by jenlampton** [comment]
I don't know, I haven't run into that. Are the file-imports set up to run through cron? If so I'd imagine yes.

**Comment by bradbulger** [comment]
I tried to figure out what the Drupal 7 version was doing differently - it's somewhere in the weeds of importer config storage, but I couldn't find where it should be storing the state.

**Comment by jenlampton** [comment]
I think I did the same and realized it was not the quickfix I had envisioned!

**Comment by herbdool** [comment]
I've got a PR if anyone wants to test https://github.com/backdrop-contrib/feeds/pull/27

I think this got missed when converting it from using ctools so hopefully this does the job. One thing to test is that it is actually disabled, ie. doesn't run in cron.

**Comment by herbdool** [comment]
I believe it works, though might be some follow-up menu route cache clearing. Not 100% certain there's another issue or not.

**Comment by herbdool** [comment]
Merged
