### ISSUE TITLE
Feeds should not mark submodules as `required`, as this hides the module from the module UI.

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/feeds#141]
When you enable a submodule like `feeds_entity_processor` and create an importer that uses it, Feeds will mark the submodule as `required`, which effectively hides the module from the module list at `admin/modules`.

Instead, Feeds should mark it as `disabled`, which disables the checkbox. (An unfortunate choice of word, as `disabled` does **not** disable the module, but rather the checkmark).

**Comment by argiepiano** [comment]
PR https://github.com/backdrop-contrib/feeds/pull/142 ready for review.

**Comment by argiepiano** [comment]
Again a test failure - no time to check, but this may be unrelated.

**Comment by MegaChriz** [comment]
This "required" mark was added to avoid modules accidentally getting disabled while they were still in use by importers. I'm not familiar with Backdrop yet, but the idea is that you are not allowed to disable the module in question (via the UI or on the command line [for example: using drush, not sure if drush is compatible with backdrop]) until all importers that depend on it are removed. If the "disabled" mark still preserves this behavior, then that's great!

See here the issue in which the "required" mark was added: https://www.drupal.org/node/2379407

At first glance, the test failures look unrelated. I saw some messages about classes that could not be found. Based on your changes, I would find it highly unlikely that that would result in tests not be able to find classes.

**Comment by argiepiano** [comment]
Thanks, @MegaChriz!! Yes, in BAckdrop, the key `disabled` disables the checkbox and prevents disabling the module. It's used by the `field` core module to avoid disabling it when there are fields. See [this line](https://github.com/backdrop/backdrop/blob/909f50d6b047f52ca65d2ecef0cab2fbecd74a07/core/modules/field/field.module#L331)

**Comment by herbdool** [comment]
Merged
