### ISSUE TITLE
Theme for the local action 

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#144]
The "Import" link gets added to the local actions section but it's themed as a local task -- this shows up particularly in Gin:

 - https://github.com/backdrop-contrib/gin/issues/71

Changing it to use `menu_local_action` as the theme matches the "Add content" link that it is positioned next to:

![CleanShot 2024-01-24 at 11 27 55@2x](https://github.com/backdrop-contrib/feeds/assets/871421/e8cc6118-b46c-4cc7-8e8c-8b73dba323ba)

**Comment by laryn** [comment]
I've submitted a PR here.

**Comment by herbdool** [comment]
This seems okay to me.
