### ISSUE TITLE
PHP 8.2 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#150]
PHP 8.2 compatibility issues:
I'm running a feeds import using the feeds_jsonpath_parser module, and I get two feeds related errors during the import.

The second error is

```
Deprecated function: Creation of dynamic property FeedsHTTPCacheItem::$from_cache is deprecated in feeds_http_request() (line 345 of /feeds/libraries/http_request.inc).
```

I've tracked this problem down to the fact that we're setting a `from_cache` property on data that was returned from `cache_get()`.  Backdrop's cache system doesn't have a `from_cache` property, so maybe there's another way to send this information down stream?

It looks like the only place this property is used is in tests, so for now, I've commented it out in my code :D 
<img width="1131" alt="Screenshot 2024-09-18 at 6 48 22 PM" src="https://github.com/user-attachments/assets/f407b933-11f4-44ea-b952-e117c4702f9a">

**Comment by herbdool** [comment]
I've added the `#[AllowDynamicProperties]` attribute.
