### ISSUE TITLE
Include Feeds Preview

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/feeds#151]
This is a pretty useful module: https://www.drupal.org/project/feedspreview. I think it should be included in Feeds to reduce the friction of discovery.

**Comment by MegaChriz** [comment]
It is indeed. Thank you! 😊

Someday I want to include a port of that to the modern Drupal version of Feeds too.

**Comment by herbdool** [comment]
@MegaChriz actually thank you for all your work on the Drupal version! It's been pretty useful for a bunch of Backdrop users.

I was wavering between including it as a sub-module, but I might just include it as core functionality, enabled on all Feeds installs. Which means I won't be able to preserve the git history (unless I include it as a sub-module and then move the code?)

**Comment by MegaChriz** [comment]
I think that the git history is less important. For the modern Drupal version of Feeds, I also intend to add it as core functionality eventually, so I think it makes sense to do the same for the Backdrop version.

**Comment by herbdool** [comment]
Fair enough. At the least I'll make sure the credit and the last commit are noted. I suppose there won't be much work on the D7 version anymore.

**Comment by MegaChriz** [comment]
The D7 version of Feeds is still supported, but I'm indeed no longer actively working on it. So yes, I expect that changes to it will be rare. Maybe a few commits a year? After Drupal 7 is EOL in January 2025, I do not intend to completely ignore new issues of the D7 version, so there can still commits happen to it in 2025.

**Comment by MegaChriz** [comment]
Oh wait, you mean the D7 version of Feeds Import Preview? Yes, it is unlikely it will get any further changes. Unless an other contributor comes along to make reasonable changes, then I may commit these.

I see that there are open issues with patches from a long time ago in the issue queue. There could be something useful in there for the Backdrop version.

**Comment by herbdool** [comment]
Correct, I meant Feeds Import Preview.

I ended up merging in the repo and then moving the code around since it wasn't too difficult. Though I did messing something up with the first rebase before merging my PR, so had to add a follow-up. Plus will need to fix the tests.
