### ISSUE TITLE
Put FeedsState class in autoload?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#156]
I happened to notice that `FeedsState` is not included in `hook_autoload_info()`. Is there any reason not to add it?

**Comment by laryn** [comment]
PR added.

**Comment by argiepiano** [comment]
I think it should be included  in autoload. It looks like the object is created by `FeedSource`, which lives in the same file - this explains why this oversight had not created issues so far.

**Comment by herbdool** [comment]
Good catch @laryn.
