### ISSUE TITLE
Node processor mapping doesn't seem to recognize Email fields

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#18]
The node processor mapping page doesn't seem to recognize Email fields. (They don't show up as an option  in the Target dropdown).

**Comment by klonos** [comment]
Noting that this seems to be a blocker for people trying to do migrations from D7.

**Comment by herbdool** [comment]
I'm guessing because this file was in the email module https://git.drupalcode.org/project/email/blob/7.x-1.x/email.feeds.inc and can be put into this module now.

**Comment by herbdool** [comment]
I created a PR. I'm pretty confident it works so I'm merging.
