### ISSUE TITLE
Add 'Import' to admin menu

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds#19]
I've always found it annoying that there doesn't seem to be a link anywhere to the 'Import' page (apart from being partially hidden on the first page of the feed configuration form). I'm constantly having to access it by typing in the URL manually.

Assuming I haven't missed something obvious, I'd like to suggest adding a link to the Import page in the Administration Menu. It seems to me that the Content section would be a good candidate:

![Import](https://user-images.githubusercontent.com/2385329/56057758-51b04800-5d68-11e9-95f1-d367171ecf26.png)

**Comment by herbdool** [comment]
Agreed, though I'm wondering if it means the path has to change to `admin/content/import` to show up there. Right now it's just `import`. Though I have no idea why they chose that path, it doesn't make much sense.

**Comment by ghost** [comment]
The URL for the 'Add content' menu item under 'Content' is `node/add`which doesn't match the `admin/content/*` syntax, so I'm sure it'll work fine as just `import`.
