### ISSUE TITLE
Feeds News requires Features

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#20]
I assume that means it's not ported/tested?

![Screen Shot 2019-05-03 at 12 34 15 AM](https://user-images.githubusercontent.com/871421/57121159-459e2180-6d3b-11e9-879a-1d40645ef65f.jpg)

**Comment by herbdool** [comment]
I propose deleting this sub module until such time that someone finds a workaround. I doubt it will be done with Features.

**Comment by laryn** [comment]
Sounds appropriate to me.
