### ISSUE TITLE
Upgraded Feeds from Drupal 7 not seamless

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#21]
As [noted here](https://forum.backdropcms.org/forum/cant-create-feeds-d7-upgrade-site), I had to do some troubleshooting after trying to use Feeds on a D7->Backdrop upgrade and in the end I had to end up completely uninstalling on Backdrop and then reactivating. The config file was full of NULL values, which is (I think) what was causing my problem.

```
{
    "_config_name": "feeds.settings",
    "feeds_reschedule": null,
    "feeds_debug": null,
    "feeds_importer_class": null,
    "feeds_library_dir": null,
    "default_feeds_importer": null,
    "menu_rebuild_needed": null,
    "feeds_source_class": null,
    "http_request_timeout": null,
    "proxy_server": null,
    "proxy_port": null,
    "proxy_username": null,
    "proxy_password": null,
    "proxy_auth_method": null,
    "feeds_never_use_curl": null,
    "feeds_process_limit": null,
    "default_nodes_main": "10"
}
```

The first error I got was:

> Fatal error: Class name must be a valid object or a string in backdrop/modules/contrib/feeds/includes/FeedsConfigurable.inc on line 64

Debugging that with [Jen's fix here](https://github.com/backdrop-contrib/feeds/issues/12#issue-354859102) gave me this:

> Error: Call to a member function configFormValidate() on null in feeds_ui_create_form_validate() (line 193 of /path/modules/feeds/feeds_ui/feeds_ui.admin.inc).

And at that point after further debugging I realized the config file may be the issue and just nuked it and reinstalled.

---------
https://github.com/backdrop-contrib/feeds/pull/29

**Comment by herbdool** [comment]
I've fixed the variables. Not only for the upgrade but also to ensure it's using the core config or state where needed. Anyone interested in testing? https://github.com/backdrop-contrib/feeds/pull/29

**Comment by laryn** [comment]
LGTM by sight, though I don't have a handy dev/database to actually test the upgrade on right now.

**Comment by herbdool** [comment]
Thanks @laryn. I think it's safe to merge.
