### ISSUE TITLE
Does not recognize the Telephone field

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/feeds#24]
The drop down list of mapping doesnt have the Telephone field as option

**Comment by herbdool** [comment]
Does such an option exist in Drupal 7's version? I'm guessing at the very least you'd need a Telephone module.

**Comment by mue368** [comment]
I've installed the Backdrop Telephone module but also after this I've noticed that there wasn't an option to map the telephone fields to a feed.

**Comment by herbdool** [comment]
I think Telephone module needs to add support for feeds. I don't see it in the module. I'm going to close the issue here.
