### ISSUE TITLE
Want help maintaining?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/feeds#25]
@docwilmot do you want help maintaining?

**Comment by docwilmot** [comment]
@herbdool I would be very happy for help. Incidentally that goes for every module or project I've ported, so officially I have no problem at all if you want to merge PRs on my projects. You have more experience and expertise than I do, I'd never say no to that.

**Comment by herbdool** [comment]
@docwilmot excellent. I wouldn't say I have more experience/expertise. Just different. You've implemented much bigger features than I have.
