### ISSUE TITLE
Too few arguments to function node_unpublish_action()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#35]
> Too few arguments to function node_unpublish_action(), 1 passed in /path/modules/feeds/plugins/FeedsNodeProcessor.inc on [line 412](https://github.com/backdrop-contrib/feeds/blob/1.x/plugins/FeedsNodeProcessor.inc#L412) and exactly 2 expected

This is on a cron run while testing an RSS feed import. I suspect the setting to unpublish previously imported nodes if they no longer exist was set.

**Comment by laryn** [comment]
It looks like it is expecting `$context` to be passed as a second variable:
https://api.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_unpublish_action/1

**Comment by herbdool** [comment]
Doesn't seem much point in using this action when we could just unpublish it directly. `node_unpublish_action` should only be used in context of actions for a View.

**Comment by herbdool** [comment]
Fixed
