### ISSUE TITLE
"deprecated" notice in taxonomy import

### ISSUE THREAD

**Issue by sternhagel** [backdrop-contrib/feeds#49]
When importing taxonomy references and mapping them by ID, there's a deprecation warning:

> The function taxonomy_feeds_set_target() (taxonomy.inc:105) called deprecated function taxonomy_vocabulary_machine_name_load(). It will be removed in the next major release of Backdrop.

This should probably be fixed before the next major Backdrop release.

**Comment by herbdool** [comment]
Thanks @sternhagel, I've updated the function.
