### ISSUE TITLE
Undefined property error when importing taxonomy terms

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/feeds#50]
Just created an import feed to populate a node type with taxonomy terms and got an error:

```
Notice: Undefined property: stdClass::$tid a taxonomy_feeds_set_target() (línia 160 de /modules/feeds/mappers/taxonomy.inc)
```
This error prevents to fill in the taxonomy terms during the import.

Will fill in a PR with the solution I found.

**Comment by herbdool** [comment]
I merged an identical PR so closing.
