### ISSUE TITLE
Update description of 'Update existing nodes' setting

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds#56]
In D7, they updated the description of the 'Update existing nodes' options here: https://git.drupalcode.org/project/feeds/commit/a966aba This was to better explain the differences between the 'Replace existing nodes' and 'Update existing nodes' options.

I suggest we do something similar, as this always confuses me.

**Comment by herbdool** [comment]
@BWPanda I created a PR, do you want to do a quick test?

**Comment by ghost** [comment]
Works well, thanks!

![image](https://user-images.githubusercontent.com/2385329/87732071-4ec7c100-c80f-11ea-84f6-88a39fcaa1e9.png)
