### ISSUE TITLE
Feeds does not map created date, URL or author correctly, uses current date, current logged in user and creates URL instead

### ISSUE THREAD

**Issue by Egarbeil** [backdrop-contrib/feeds#69]
Running into a big issue with Feeds importer - it is overwriting the Author and Post Date assigned in mapping and replacing with current logged in user and current date - this is a **BIG issue** for this client, since the announcements are sorted by date and the URL's are assigned by date - it's losing all that information on import. And there are a LOT of announcements - I can't fix them all manually. **HELP!!!**

Here's the field mappings. The URL, Title, Author and Date are critical: post-mapping.jpeg
![post-mapping](https://user-images.githubusercontent.com/41450710/90052774-a1c65400-dca7-11ea-8c4e-642b83e44eef.jpeg)

**Comment by laryn** [comment]
I can't troubleshoot much due to other work, but some questions that come to mind:

 - Do the users exist in the user table?
 - Is the date format and author format what the importer is expecting?
 - Any errors in the logs?

**Comment by Egarbeil** [comment]
Yes, the user ID exists in the table.  Not sure what date format it is expecting, the author format (UID) is correct.  There are no errors in the logs.  It’s as if the feeds are completely ignoring mapping for those fields and only using system node defaults.


Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by docwilmot** [comment]
I'll have a look in a minute.

**Comment by Egarbeil** [comment]
I checked and the date format is long in the import file (default export).  Not sure what the feeds importer is expecting for that field (Post Date).  I couldn't find any documentation on it.

**Comment by Egarbeil** [comment]
> I'll have a look in a minute.

@docwilmot - THANK YOU!  I'm hoping it's a simple fix.  The critical piece is the date created.  I can fudge the Author UID in the database if I have to, although I would rather not.  I am going to have the same issue with news posts and blog posts so fixing it here is a big deal, with 5+ years of announcements, even without the news and blog posts.

**Comment by Egarbeil** [comment]
Issue update:  I found that I had to format the dates to "mm/dd/yyyy" and then add one day.  When I just imported the date as is,  it set the time to mm/dd/yyyy 00:00 and subtracted 4 hours - so all my dates were off by one.  It's rather kludgey, but it worked for me as a quick solution.

**Comment by ghost** [comment]
@Egarbeil I'm using Feeds on a project currently. While I'm not worried about the author, I do have the Post Date from the D7 site importing into the Post Date in Backdrop. I have the same setup as you in Feeds, and in D7 I have the post date exporting as such:
![image](https://user-images.githubusercontent.com/2385329/90071784-886de800-dd39-11ea-93e3-3d3336a1318b.png)

I think the thing is to make sure the data being imported is in the right format for Backdrop. E.g. dates should be a Unix timestamp (PHP's `U` date format).

As for authors, maybe confirm you're importing the UID (as opposed to a name, etc. Also, try changing the UID integer to a string, or vice versa (that may have an effect on it).

Hope that helps.

**Comment by Egarbeil** [comment]
Peter,

I hadn’t tried the unix timestamp. I will give that a shot.  The user ID imports fine as long as I use the UID from the new site, so that’s not an issue.  I have a find and replace for those, so it’s not a problem.  It was the dates that were making my life miserable.  The workaround I came up with was kludgy, but it worked.

There is nowhere in the documentation that says to use the unix timestamp, so that’s very frustrating - the glossary states “mm/dd/yyyy” and it took me forever to find that on drupal.org.  When I used feeds on D7 it wasn’t a problem.   How did you figure it out?

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by ghost** [comment]
> How did you figure it out?

I'm not sure. I think I've just always done that (tried to export/import content in the format the new site needs it in). As in, dates are saved in Drupal/Backdrop databases as unix timestamps, so you can't go wrong there. Other formats might work, but I think native formats are best.

**Comment by Egarbeil** [comment]
That makes sense. I think I just started with the default output from the view.

Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by docwilmot** [comment]
I just tried a datetime string and it imported (it converted the timezone though). So doesnt need to be unix. I used `2013-03-01T16:15:09+01:00`(a random string off the net) but I saved that in notepad because excel converts everything.

So you need it in a format that Backdrop can recognise

**Comment by sbgraphicdesign** [comment]
I've used Feeds to import data into a number of sites in backdrop and Drupal. You have to make sure that your data is correctly formatted in the import feed or file first. I think Feeds tends to import data directly to the database, in a way that's different from entering in the Node form, so I've often found looking at the database tables can help to figure out how the data is stored. And then it's a case of test, test and test!

One module that can help make importing using Feeds easier in Drupal is Feeds Tamper, which looks like is finally available for Backdrop: https://github.com/backdrop-contrib/feeds_tamper. I've not tested it in Backdrop myself, but could be worth a look at.

**Comment by Egarbeil** [comment]
Stuart,

I’ve used feeds plenty D6 - D7 and D7-D7.  There is a difference from how Backdrop handles dates to how Drupal handles dates, and the required date formats are different.  Feeds does import to the database, but it maps and configures it first.   There’s some information lacking in the documentation on how Backdrop handles things before it imports them.  (For example, it doesn’t use the local time zone set up in Config - System  like Drupal Feeds does - it uses GMT) that are causing me problems because I have to find them the hard way.  

Feeds tamper won’t help in this case, I don’t need the data massaged upon import.  That module is for particular use cases, such as when you have multiple value fields or field collections.  

Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by Egarbeil** [comment]
The problem is the timezone at this point.  That’s huge for me because I need the correct dates and times.  There should be some way to force feeds to use the timezone defined in Config-system instead of GMT times.


Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by herbdool** [comment]
There's been a recent fix to dates: https://github.com/backdrop-contrib/feeds/issues/77 so I've tested this issue against dev. I used this adapted csv file from the feeds automated tests. Everything worked successfully.

```
"guid","title","created","end","datetime_start","datetime_end","author"
1,"Lorem ipsum",1251936720,1351936720,"1955-11-05 12:00","1955-11-05 15:00","admin"
2,"Ut wisi enim ad minim veniam",1251932360,1351932360,"21-10-2015 23:29","22-10-2015 2:29","test1"
3,"Nam liber tempor",1190835120,1390835120,"2018-02-09T00:00:00.0000000Z","2018-02-10T22:00:00.0000000Z","test1"
```

Note that it uses a variety of date formats. And it using the username and not the uid. I assume that uid would also work.

Since everything mapped as expected I'm going to close this issue. If you also want to test this, use the current 1.x-1.1.1 release and let me know if it's still not working.
