### ISSUE TITLE
Fatal Error when exporting feeds

### ISSUE THREAD

**Issue by Dogbombs** [backdrop-contrib/feeds#7]
`Error: Cannot use object of type stdClass as array in feeds_export() (line 962 of /modules/feeds-1.x/feeds.module).`

Error thrown when selecting a Feeds Importer and choosing "Export" from the available options.

**Comment by docwilmot** [comment]
I've redirected the export tab to the main Backdrop config export page. That will avoid the error.
We need to more broadly purge the old CTools export code eventually.
