### ISSUE TITLE
Make 'Enabled' column the first column of the 'Feeds importers' table

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds#70]
It feels weird not having the 'Operations' column be the last column in the table:

![image](https://user-images.githubusercontent.com/2385329/90579757-56adc300-e20a-11ea-8a22-d9159862f608.png)

I suggest moving the 'Enabled' column to the left so it's the first column. This would then match how the Modules table is arranged:

![image](https://user-images.githubusercontent.com/2385329/90579838-86f56180-e20a-11ea-8e57-242e3fdbf1a9.png)

**Comment by herbdool** [comment]
I decided to make it more like the core menu UI where the checkbox is just before operations. @BWPanda want to take a look?

![Screenshot from 2021-01-26 15-33-00](https://user-images.githubusercontent.com/1071483/105901761-cf038600-5feb-11eb-9b0f-ef6a88a5aa1e.png)

**Comment by ghost** [comment]
That looks better.
