### ISSUE TITLE
File upload field display issue

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds#73]
There seems to be an issue with the file upload field on the Import form:

![image](https://user-images.githubusercontent.com/2385329/99924713-73204500-2d8f-11eb-8b1f-e23a1fe9c90e.png)

This is because it's floated left:

```css
.feeds-file-upload {
    float: left;
}
```

I'm not sure what this float is for - whether it can be safely removed or whether the container div needs to be cleared. In any case, something needed here to make it display properly.

**Comment by herbdool** [comment]
@BWPanda want to test the PR?

**Comment by ghost** [comment]
Perfect! 👍🏻
