### ISSUE TITLE
Missing DateObject class

### ISSUE THREAD

**Issue by Radcliffe** [backdrop-contrib/feeds#77]
When I attempt to import a CSV feed containing dates, the import fails with the following error:

Error: Class 'DateObject' not found in _date_feeds_get_date_object() (line 210 of [...]/modules/contrib/feeds/mappers/date.inc).

I am unable to find a definition for the `DateObject` class in my codebase. Is there another module that provides it?

I am running Backdrop 1.18.0 with PHP 7.2.34.

It was working for me before I updated Feeds to 1.1.0.

**Comment by Radcliffe** [comment]
In Drupal 7, the `DateObject` class is provided by the `date_api` module, which is a submodule of the `date` module. It appears that the `date_api` module has not been ported to Backdrop CMS.

**Comment by herbdool** [comment]
Looks like it is now called `BackdropDateTime` https://api.backdropcms.org/change-records/date-date-popup-and-date-views-modules-now-included-core

**Comment by herbdool** [comment]
@Radcliffe I've merged a PR into the repo. I haven't created a release yet - care to test the latest commits to see if they fix your issues?

**Comment by Radcliffe** [comment]
Works for me!

**Comment by herbdool** [comment]
Good, thanks.
