### ISSUE TITLE
PHP Notice: Undefined index: disabled

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/feeds#86]
After updating from `1.x-1.0.1-beta` to `1.x-1.1.1` I see this error repeated on every page of my site, once for each feeds importer I have (so, 4 times on this site).

```
Notice: Undefined index: disabled in feeds_load_importer_object() (line 1638 of backdrop/modules/contrib/feeds/feeds.module).
```

**Comment by bradbulger** [comment]
Could we get this into a release?
