### ISSUE TITLE
Taxonomy mapper issues

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds#89]
I had to make a few tweaks to get the taxonomy mapper working as expected. PR coming for review.

**Comment by simone960** [comment]
Thanks @laryn ! 

I initially encountered the error of "Missing bundle property on entity of type taxonomy_term" when importing content (Node import) with several term reference fields. Your fix works for me and I can import without issue now.  Great thanks !

**Comment by simone960** [comment]
By the way, I notice there's a warning recorded in the "Recent log messages" after a successful import is made.

`Warning: Illegal offset type in taxonomy_feeds_set_target() (line 109 of /var/........../modules/feeds/mappers/taxonomy.inc).`

**Comment by laryn** [comment]
Here's another WFM: https://github.com/backdrop-contrib/feeds/pull/90#issuecomment-821311641

**Comment by oadaeh** [comment]
@simone960: https://github.com/backdrop-contrib/feeds/issues/91
