### ISSUE TITLE
Remote File Import Fails With Exception

### ISSUE THREAD

**Issue by bobchristenson** [backdrop-contrib/feeds#9]
When attempting to pull in remote files via a CSV url, I get the following:
`Exception: Download of http://example.com/sites/default/files/05202018.mp3 failed with code -1. in /Drupal/localsite/modules/contrib/feeds/plugins/FeedsParser.inc:424

Stack trace:

#0 /Drupal/localsite/modules/contrib/feeds/plugins/FeedsParser.inc(483): FeedsEnclosure->getContent()

#1 /Drupal/localsite/modules/contrib/feeds/mappers/file.inc(127): FeedsEnclosure->getFile('public://audio/')

#2 /Drupal/localsite/modules/contrib/feeds/plugins/FeedsProcessor.inc(806): file_feeds_set_target(Object(FeedsSource), Object(Node), 'field_audio:uri', Array, Array)

#3 /Drupal/localsite/modules/contrib/feeds/plugins/FeedsProcessor.inc(752): FeedsProcessor->mapToTarget(Object(FeedsSource), 'field_audio:uri', Object(Node), Array, Array)

#4 /Drupal/localsite/modules/contrib/feeds/plugins/FeedsProcessor.inc(302): FeedsProcessor->map(Object(FeedsSource), Object(FeedsParserResult), Object(Node))

#5 /Drupal/localsite/modules/contrib/feeds/includes/FeedsSource.inc(399): FeedsProcessor->process(Object(FeedsSource), Object(FeedsParserResult))

#6 /Drupal/localsite/modules/contrib/feeds/feeds.module(207): FeedsSource->import()

#7 /Drupal/localsite/core/includes/batch.inc(251): feeds_batch('import', 'sermon_importer', 0, Array)

#8 /Drupal/localsite/core/includes/batch.inc(111): _batch_process()

#9 /Drupal/localsite/core/includes/batch.inc(85): _batch_do()

#10 /Drupal/localsite/core/modules/system/system.admin.inc(2198): _batch_page()

#11 /Drupal/localsite/core/includes/menu.inc(582): system_batch_page()

#12 /Drupal/localsite/core/modules/layout/layout.module(441): menu_default_route_handler(Array)

#13 /Drupal/localsite/core/includes/menu.inc(529): layout_route_handler(Array)

#14 /Drupal/localsite/index.php(21): menu_execute_active_handler()

#15 {main}
`

and:
`Invalid enclosure <em class="placeholder">http://example.com/sites/default/files/05202018.mp3</em>`

I confirmed the file is there and publicly readable...where were else could this problem be coming from?

**Comment by docwilmot** [comment]
TBH dont think I ever tested remote files. I'd need to look into it, soon as I could. You desperately need this?

**Comment by bobchristenson** [comment]
Yup, I'll need it to be able to migrate a site from D7....On a hunch I increased my memory and upload limits and that error went away.  Now I get:
`Notice: Undefined index: module in feeds_system_info_alter() (line 756 of /Drupal/localsite/modules/contrib/feeds/feeds.module).`

**Comment by ghost** [comment]
@bobchristenson Here's an issue for that second error with a PR: https://github.com/backdrop-contrib/feeds/issues/13

**Comment by bobchristenson** [comment]
Here we are, months later, and I tried with the latest versions of Feeds...and everything seems to be working now.  I think those original errors were server memory errors.  The later error, referenced just above this comment, must have been resolved (?) as I"m not seeing it anymore. Closing this issue, reopen if you see this behavior again.
