### ISSUE TITLE
Add the ability for "Reference" items to be included in the mapper.

### ISSUE THREAD

**Issue by philsward** [backdrop-contrib/feeds#97]
Using the "Reference" module, I used it for adding taxonomy terms to a page (as opposed to the OOTB Term Reference field). Unfortunately, these aren't being pulled in by the feeds mapper.

Since Term Reference will some day go away, I would prefer to use the Reference module instead of Term Reference.

**Comment by jenlampton** [comment]
I think you want this issue: https://github.com/backdrop-contrib/reference/issues/51 (feeds support for reference module)
