### ISSUE TITLE
Error: Call to undefined function profile_user_categories()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/feeds#98]
This error is thrown when `profile` module is enabled, and while trying to create a new feed importer for users - specifically when clicking User processor > Mapping in the Feeds importers UI

**Comment by PepeMty** [comment]
Hey @argiepiano 
Almost 2 years later I have the very same issue.
Did you managed to solve it...?

**Comment by argiepiano** [comment]
I've looked into this. The file `mappers/profile.inc` provided by feeds is actually not needed. It was originally used by Feeds to provide integration with Drupal 7's `profile`, which was a core module that was deprecated in D7. Unfortunately, the Backdrop version of D7's `profile2` module is called `profile` in BAckdrop. This confuses Feeds into assuming it needs to use the code in that file to integrate with Backdrop's `profile` - but that code doesn't work, as it was intended for D7's old, deprecated `profile` module (not `profile2`).

So, you can safely delete `mappers/profile.inc`, since it's actually not used by feeds and Backdrop's profile.

**Comment by argiepiano** [comment]
Just to add to the above: Backdrop's `profile` does not integrate with `feeds`. In D7, that integration was handled by [Feeds Profile2](https://www.drupal.org/project/feeds_profile2). That needs to be ported to Backdrop. It shouldn't be hard.

**Comment by argiepiano** [comment]
PR #137 provided and ready for review.
